include_guard(GLOBAL)

cmake_policy(PUSH)
cmake_policy(SET CMP0121 NEW)

function(_shadertool_validate_shader_profile backend profile)
    if(NOT profile MATCHES "^[0-9]+_[0-9]+$")
        message(FATAL_ERROR "invalid ${backend} shader profile suffix: ${profile}")
    endif()
    if(backend STREQUAL FXC)
        if(NOT profile MATCHES "^5_[01]$")
            message(FATAL_ERROR "FXC requires shader profile 5_0 or 5_1, got ${profile}")
        endif()
    elseif(NOT profile MATCHES "^[6-9]_[0-9]+$")
        message(FATAL_ERROR "${backend} requires shader profile 6_0 or newer, got ${profile}")
    endif()
endfunction()

function(_shadertool_resolve_shader_compiler backend output_variable)
    unset(compiler)
    if(backend STREQUAL FXC)
        if(NOT WIN32)
            message(FATAL_ERROR "FXC shader backend is unsupported on native Unix; use the Win32 ShaderTool through the Wine toolchain")
        endif()
        if(NOT FXC_EXECUTABLE)
            find_program(compiler "fxc" REQUIRED)
        else()
            set(compiler "${FXC_EXECUTABLE}")
        endif()
    else()
        if(NOT DXC_EXECUTABLE)
            find_program(compiler "dxc" REQUIRED)
        else()
            set(compiler "${DXC_EXECUTABLE}")
        endif()
    endif()
    set(${output_variable} "${compiler}" PARENT_SCOPE)
endfunction()

function(_shadertool_generate_shader_objects output_variable source_variable header_dir_variable)
    set(options OUTPUT_NAME_USE_ENTRY)
    set(oneValueArgs TARGET SHADER_PROFILE CONFIG_FILE OUTPUT_DIRECTORY TYPE BACKEND
        COMPILER OUTPUT_SUFFIX)
    set(multiValueArgs INCLUDE_DIRECTORIES EXTRA_FLAGS)
    cmake_parse_arguments(shadertool "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(shadertool_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "unknown shader object arguments: ${shadertool_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT shadertool_TARGET OR NOT shadertool_CONFIG_FILE OR
       NOT shadertool_BACKEND OR NOT shadertool_COMPILER)
        message(FATAL_ERROR
            "shader object generation requires TARGET, CONFIG_FILE, BACKEND, and COMPILER")
    endif()
    if(NOT shadertool_TYPE)
        set(shadertool_TYPE HEADER)
    endif()
    string(TOUPPER "${shadertool_TYPE}" shadertool_TYPE)
    if(NOT shadertool_TYPE STREQUAL BINARY AND NOT shadertool_TYPE STREQUAL HEADER)
        message(FATAL_ERROR "shader object TYPE must be BINARY or HEADER")
    endif()
    if(NOT shadertool_OUTPUT_DIRECTORY)
        set(shadertool_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    endif()
    cmake_path(ABSOLUTE_PATH shadertool_OUTPUT_DIRECTORY NORMALIZE OUTPUT_VARIABLE shadertool_OUTPUT_DIRECTORY)
    if(NOT shadertool_SHADER_PROFILE)
        if(shadertool_BACKEND STREQUAL FXC)
            set(shadertool_SHADER_PROFILE 5_0)
        else()
            set(shadertool_SHADER_PROFILE 6_0)
        endif()
    endif()
    _shadertool_validate_shader_profile("${shadertool_BACKEND}" "${shadertool_SHADER_PROFILE}")

    cmake_path(ABSOLUTE_PATH shadertool_CONFIG_FILE NORMALIZE
        OUTPUT_VARIABLE config_file_path)
    if(NOT EXISTS "${config_file_path}")
        message(FATAL_ERROR "shader config file does not exist: ${config_file_path}")
    endif()
    cmake_path(GET config_file_path PARENT_PATH config_file_dir)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
        "${config_file_path}")
    file(STRINGS "${config_file_path}" shader_cfg_lines REGEX "^[ \t]*[^# \t].*$")

    string(TOLOWER "${shadertool_BACKEND}" backend_name)
    set(output_root "${shadertool_OUTPUT_DIRECTORY}/${backend_name}")
    set(intermediate_root
        "${CMAKE_CURRENT_BINARY_DIR}/__shadertool_${shadertool_TARGET}/${backend_name}")
    set(extra_options ${shadertool_EXTRA_FLAGS})
    foreach(include_dir IN LISTS shadertool_INCLUDE_DIRECTORIES)
        cmake_path(ABSOLUTE_PATH include_dir NORMALIZE OUTPUT_VARIABLE include_dir)
        list(APPEND extra_options -I "${include_dir}")
    endforeach()

    set(output_files)
    set(entry_files)
    foreach(config_line IN LISTS shader_cfg_lines)
        separate_arguments(command_line NATIVE_COMMAND "${config_line}")
        list(LENGTH command_line command_length)
        if(command_length LESS 2)
            message(FATAL_ERROR "invalid shader config line: ${config_line}")
        endif()
        list(GET command_line 0 entry_file_name)
        list(REMOVE_AT command_line 0)
        cmake_path(ABSOLUTE_PATH entry_file_name BASE_DIRECTORY "${config_file_dir}"
            NORMALIZE OUTPUT_VARIABLE entry_file_path)
        cmake_path(GET entry_file_path PARENT_PATH entry_file_dir)
        cmake_path(RELATIVE_PATH entry_file_dir BASE_DIRECTORY "${config_file_dir}"
            OUTPUT_VARIABLE entry_file_rel_dir)
        if(entry_file_rel_dir MATCHES "^\\.\\.($|/)")
            set(entry_file_rel_dir "")
        endif()
        cmake_path(GET entry_file_name EXTENSION LAST_ONLY entry_file_ext)

        list(FIND command_line -T profile_option_index)
        if(profile_option_index EQUAL -1)
            message(FATAL_ERROR "-T <stage> missing in shader config line: ${config_line}")
        endif()
        math(EXPR profile_value_index "${profile_option_index} + 1")
        list(LENGTH command_line command_length)
        if(profile_value_index GREATER_EQUAL command_length)
            message(FATAL_ERROR "-T requires a stage in shader config line: ${config_line}")
        endif()
        list(GET command_line ${profile_value_index} shader_stage)
        if(NOT shader_stage MATCHES "^[a-z][a-z0-9]*$")
            message(FATAL_ERROR
                "shader config -T value must be an unversioned stage, got ${shader_stage}")
        endif()
        list(REMOVE_AT command_line ${profile_value_index})
        list(INSERT command_line ${profile_value_index}
            "${shader_stage}_${shadertool_SHADER_PROFILE}")

        if(shadertool_BACKEND STREQUAL SPIRV)
            if(shader_stage STREQUAL vs)
                set(stage_binding_base 0)
            elseif(shader_stage STREQUAL hs)
                set(stage_binding_base 512)
            elseif(shader_stage STREQUAL ds)
                set(stage_binding_base 1024)
            elseif(shader_stage STREQUAL gs)
                set(stage_binding_base 1536)
            elseif(shader_stage STREQUAL ps)
                set(stage_binding_base 2048)
            elseif(shader_stage STREQUAL cs)
                set(stage_binding_base 2560)
            else()
                message(FATAL_ERROR
                    "no built-in SPIR-V binding layout for shader stage: ${shader_stage}")
            endif()
            math(EXPR sampler_binding "${stage_binding_base} + 128")
            math(EXPR constant_binding "${stage_binding_base} + 256")
            math(EXPR storage_binding "${stage_binding_base} + 384")
            list(APPEND command_line
                -fvk-t-shift "${stage_binding_base}" 0
                -fvk-s-shift "${sampler_binding}" 0
                -fvk-b-shift "${constant_binding}" 0
                -fvk-u-shift "${storage_binding}" 0)
        endif()

        list(FIND command_line -Vn variable_option_index)
        if(variable_option_index GREATER -1 AND shadertool_OUTPUT_SUFFIX)
            math(EXPR variable_value_index "${variable_option_index} + 1")
            list(GET command_line ${variable_value_index} variable_name)
            string(APPEND variable_name "${shadertool_OUTPUT_SUFFIX}")
            list(REMOVE_AT command_line ${variable_value_index})
            list(INSERT command_line ${variable_value_index} "${variable_name}")
        endif()

        if(shadertool_OUTPUT_NAME_USE_ENTRY)
            list(FIND command_line -E entry_option_index)
            if(entry_option_index EQUAL -1)
                message(FATAL_ERROR "-E <entry> missing in shader config line: ${config_line}")
            endif()
            math(EXPR entry_value_index "${entry_option_index} + 1")
            list(LENGTH command_line command_length)
            if(entry_value_index GREATER_EQUAL command_length)
                message(FATAL_ERROR "-E requires a value in shader config line: ${config_line}")
            endif()
            list(GET command_line ${entry_value_index} output_stem)
            set(output_name "${output_stem}${entry_file_ext}")
            set(output_relative_dir "${entry_file_rel_dir}")
        else()
            cmake_path(GET entry_file_name FILENAME output_name)
            set(output_relative_dir "${entry_file_rel_dir}")
        endif()
        string(APPEND output_name "${shadertool_OUTPUT_SUFFIX}")

        if(shadertool_TYPE STREQUAL HEADER)
            string(APPEND output_name ".h")
            set(output_flag -Fh)
        else()
            string(APPEND output_name ".bin")
            set(output_flag -Fo)
        endif()
        set(output_dir "${output_root}/${output_relative_dir}")
        set(output_path "${output_dir}/${output_name}")
        set(dep_dir "${intermediate_root}/${output_relative_dir}")
        set(dep_path "${dep_dir}/${output_name}.depends")

        list(FIND command_line -nologo nologo_index)
        if(nologo_index EQUAL -1)
            list(APPEND command_line -nologo)
        endif()
        list(PREPEND command_line ${extra_options})
        list(APPEND command_line ${output_flag} "${output_path}")
        list(APPEND command_line -depfile "${dep_path}" "${entry_file_path}")

        if(ShaderTool_WINDOWS_WINE_CROSS)
            set(wine_command_line)
            foreach(argument IN LISTS command_line)
                if(argument MATCHES "^/")
                    list(APPEND wine_command_line "Z:${argument}")
                else()
                    list(APPEND wine_command_line "${argument}")
                endif()
            endforeach()
            set(command_line ${wine_command_line})
        endif()

        set(compiler_dependency)
        if(EXISTS "${shadertool_COMPILER}")
            set(compiler_dependency "${shadertool_COMPILER}")
        endif()
        add_custom_command(
            OUTPUT "${output_path}"
            BYPRODUCTS "${dep_path}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${output_dir}" "${dep_dir}"
            COMMAND ShaderTool "${backend_name}" -compiler "${shadertool_COMPILER}"
                ${command_line}
            WORKING_DIRECTORY "${entry_file_dir}"
            DEPENDS "${entry_file_path}" ${compiler_dependency} ShaderTool
            DEPFILE "${dep_path}"
            COMMAND_EXPAND_LISTS VERBATIM)
        list(APPEND output_files "${output_path}")
        list(APPEND entry_files "${entry_file_path}")
    endforeach()

    set(${output_variable} "${output_files}" PARENT_SCOPE)
    set(${source_variable} "${entry_files}" PARENT_SCOPE)
    if(shadertool_TYPE STREQUAL HEADER)
        set(${header_dir_variable} "${output_root}" PARENT_SCOPE)
    else()
        set(${header_dir_variable} "" PARENT_SCOPE)
    endif()
endfunction()

function(shadertool_add_shader_objects)
    set(options OUTPUT_NAME_USE_ENTRY)
    set(oneValueArgs TARGET CONFIG_FILE SHADER_PROFILE TYPE OUTPUT_DIRECTORY OUTPUT_SUFFIX)
    set(multiValueArgs BACKENDS INCLUDE_DIRECTORIES EXTRA_FLAGS)
    cmake_parse_arguments(shadertool "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    if(shadertool_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "unknown shadertool_add_shader_objects arguments: ${shadertool_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT shadertool_TARGET OR NOT shadertool_CONFIG_FILE OR NOT shadertool_BACKENDS)
        message(FATAL_ERROR
            "shadertool_add_shader_objects requires TARGET, CONFIG_FILE, and non-empty BACKENDS")
    endif()
    if(TARGET "${shadertool_TARGET}")
        message(FATAL_ERROR "shader object target already exists: ${shadertool_TARGET}")
    endif()

    set(selected_backends)
    foreach(backend IN LISTS shadertool_BACKENDS)
        string(TOUPPER "${backend}" backend)
        if(NOT backend STREQUAL FXC AND
           NOT backend STREQUAL DXC AND
           NOT backend STREQUAL SPIRV)
            message(FATAL_ERROR "unknown shader backend: ${backend}")
        endif()
        if(backend IN_LIST selected_backends)
            message(FATAL_ERROR "duplicate shader backend: ${backend}")
        endif()
        list(APPEND selected_backends "${backend}")
        if(shadertool_SHADER_PROFILE)
            _shadertool_validate_shader_profile("${backend}" "${shadertool_SHADER_PROFILE}")
        endif()
    endforeach()

    set(common_arguments TARGET "${shadertool_TARGET}"
        CONFIG_FILE "${shadertool_CONFIG_FILE}")
    if(shadertool_TYPE)
        list(APPEND common_arguments TYPE "${shadertool_TYPE}")
    endif()
    if(shadertool_OUTPUT_DIRECTORY)
        list(APPEND common_arguments OUTPUT_DIRECTORY "${shadertool_OUTPUT_DIRECTORY}")
    endif()
    if(shadertool_OUTPUT_SUFFIX)
        list(APPEND common_arguments OUTPUT_SUFFIX "${shadertool_OUTPUT_SUFFIX}")
    endif()
    if(shadertool_INCLUDE_DIRECTORIES)
        list(APPEND common_arguments INCLUDE_DIRECTORIES ${shadertool_INCLUDE_DIRECTORIES})
    endif()
    if(shadertool_EXTRA_FLAGS)
        list(APPEND common_arguments EXTRA_FLAGS ${shadertool_EXTRA_FLAGS})
    endif()
    if(shadertool_SHADER_PROFILE)
        list(APPEND common_arguments SHADER_PROFILE "${shadertool_SHADER_PROFILE}")
    endif()
    if(shadertool_OUTPUT_NAME_USE_ENTRY)
        list(APPEND common_arguments OUTPUT_NAME_USE_ENTRY)
    endif()

    set(all_outputs)
    set(all_sources)
    set(header_directories)
    foreach(backend IN LISTS selected_backends)
        _shadertool_resolve_shader_compiler("${backend}" compiler)
        _shadertool_generate_shader_objects(outputs sources header_dir
            BACKEND "${backend}" COMPILER "${compiler}" ${common_arguments})
        list(APPEND all_outputs ${outputs})
        list(APPEND all_sources ${sources})
        if(header_dir)
            list(APPEND header_directories "${header_dir}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES all_sources)
    add_custom_target("${shadertool_TARGET}" DEPENDS ${all_outputs} SOURCES ${all_sources})
    add_dependencies("${shadertool_TARGET}" ShaderTool)
    if(header_directories)
        set_property(TARGET "${shadertool_TARGET}" PROPERTY
            OBJECT_HEADER_OUTPUT_DIR "${header_directories}")
        set_property(TARGET "${shadertool_TARGET}" PROPERTY
            OBJECT_HEADER_FILES "${all_outputs}")
    endif()
endfunction()

cmake_policy(POP)
