# ShaderToolDependencies.cmake
#
# Extracts the vendored compiler packages (thirdparty/*.tgz, pinned by
# thirdparty/VERSIONS) into ${CMAKE_BINARY_DIR}/_deps/<name>/ at configure
# time and defines the IMPORTED targets ShaderTool links against:
#
#   ShaderTool::dxcompiler    (Windows + Linux)
#   ShaderTool::d3dcompiler   (Windows only; DXBC backend)
#   ShaderTool::slang         (Windows + Linux)
#
# Extraction is stamp-guarded: <dest>.stamp records the package version taken
# from the VERSIONS file (falling back to the archive's SHA256), so packages
# are re-extracted only when the pinned version changes.
#
# shadertool_copy_runtime_libraries(<target>) copies the runtime DLLs/DSOs and
# the slang standard-module directory next to $<TARGET_FILE:<target>> after
# every build (and, on non-Windows platforms, sets RPATH to $ORIGIN).
include_guard(GLOBAL)

# ---------------------------------------------------------------------------
# Locate the package directory. This module is included from three places:
#   1. the source tree            <root>/cmake/            -> <root>/thirdparty
#   2. the build-tree package     (wrapper generated by CMakeLists.txt presets
#                                  SHADERTOOL_THIRDPARTY_PACKAGE_DIR)
#   3. the install tree           <prefix>/<libdir>/cmake/ShaderTool/
#                                  -> <prefix>/share/ShaderTool/thirdparty
# ---------------------------------------------------------------------------
if(NOT SHADERTOOL_THIRDPARTY_PACKAGE_DIR)
    foreach(_shadertool_candidate
        "${CMAKE_CURRENT_LIST_DIR}/../thirdparty"
        "${CMAKE_CURRENT_LIST_DIR}/../../../share/ShaderTool/thirdparty"
        "${CMAKE_CURRENT_LIST_DIR}/../../share/ShaderTool/thirdparty")
        if(EXISTS "${_shadertool_candidate}/VERSIONS")
            set(SHADERTOOL_THIRDPARTY_PACKAGE_DIR "${_shadertool_candidate}")
            break()
        endif()
    endforeach()
endif()
if(NOT SHADERTOOL_THIRDPARTY_PACKAGE_DIR OR
   NOT EXISTS "${SHADERTOOL_THIRDPARTY_PACKAGE_DIR}/VERSIONS")
    message(FATAL_ERROR
        "ShaderTool: vendored package directory not found "
        "(looked for a thirdparty/VERSIONS next to ${CMAKE_CURRENT_LIST_DIR}); "
        "set SHADERTOOL_THIRDPARTY_PACKAGE_DIR to the directory holding the "
        "ShaderTool *.tgz packages")
endif()
cmake_path(ABSOLUTE_PATH SHADERTOOL_THIRDPARTY_PACKAGE_DIR NORMALIZE)

set(_shadertool_deps_root "${CMAKE_BINARY_DIR}/_deps")

function(_shadertool_extract_package name out_dir_variable)
    set(archive "${SHADERTOOL_THIRDPARTY_PACKAGE_DIR}/${name}.tgz")
    if(NOT EXISTS "${archive}")
        message(FATAL_ERROR "ShaderTool: vendored package not found: ${archive}")
    endif()

    # Pinned version = the package's "Upstream :" line in VERSIONS; fall back
    # to the archive hash if the VERSIONS entry cannot be parsed.
    file(READ "${SHADERTOOL_THIRDPARTY_PACKAGE_DIR}/VERSIONS" versions_content)
    string(REGEX MATCH "${name}\\.tgz[^\n]*\n[ \t]*Upstream[ \t]*:[ \t]*([^\r\n]+)"
        _shadertool_unused "${versions_content}")
    set(version "${CMAKE_MATCH_1}")
    string(STRIP "${version}" version)
    if(NOT version)
        file(SHA256 "${archive}" version)
    endif()

    set(destination "${_shadertool_deps_root}/${name}")
    set(stamp "${destination}.stamp")
    set(current "")
    if(EXISTS "${stamp}")
        file(READ "${stamp}" current)
    endif()
    if(NOT EXISTS "${destination}" OR NOT current STREQUAL version)
        message(STATUS "ShaderTool: extracting ${name}.tgz (${version})")
        file(REMOVE_RECURSE "${destination}")
        file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${destination}")
        file(WRITE "${stamp}" "${version}")
    endif()
    set(${out_dir_variable} "${destination}" PARENT_SCOPE)
endfunction()

function(_shadertool_locate_slang_module_dir base_dir)
    file(GLOB module_dirs "${base_dir}/slang-standard-module-*")
    list(LENGTH module_dirs module_dir_count)
    if(NOT module_dir_count EQUAL 1)
        message(FATAL_ERROR
            "ShaderTool: expected exactly one slang-standard-module-* directory "
            "under ${base_dir}, found: ${module_dirs}")
    endif()
    list(GET module_dirs 0 module_dir)
    set_property(GLOBAL PROPERTY SHADERTOOL_SLANG_STANDARD_MODULE_DIR "${module_dir}")
endfunction()

if(WIN32)
    _shadertool_extract_package(dxc-win-x64 _shadertool_dxc_dir)
    _shadertool_extract_package(d3dcompiler-win-x64 _shadertool_d3dcompiler_dir)
    _shadertool_extract_package(slang-win-x64 _shadertool_slang_dir)

    if(NOT TARGET ShaderTool::dxcompiler)
        add_library(ShaderTool::dxcompiler SHARED IMPORTED GLOBAL)
        set_target_properties(ShaderTool::dxcompiler PROPERTIES
            IMPORTED_IMPLIB "${_shadertool_dxc_dir}/lib/x64/dxcompiler.lib"
            IMPORTED_LOCATION "${_shadertool_dxc_dir}/bin/x64/dxcompiler.dll"
            INTERFACE_INCLUDE_DIRECTORIES "${_shadertool_dxc_dir}/inc")
    endif()

    if(NOT TARGET ShaderTool::d3dcompiler)
        add_library(ShaderTool::d3dcompiler SHARED IMPORTED GLOBAL)
        set_target_properties(ShaderTool::d3dcompiler PROPERTIES
            IMPORTED_IMPLIB "${_shadertool_d3dcompiler_dir}/lib/x64/d3dcompiler.lib"
            IMPORTED_LOCATION "${_shadertool_d3dcompiler_dir}/bin/x64/d3dcompiler_47.dll"
            INTERFACE_INCLUDE_DIRECTORIES "${_shadertool_d3dcompiler_dir}/inc")
    endif()

    if(NOT TARGET ShaderTool::slang)
        add_library(ShaderTool::slang SHARED IMPORTED GLOBAL)
        set_target_properties(ShaderTool::slang PROPERTIES
            IMPORTED_IMPLIB "${_shadertool_slang_dir}/lib/slang.lib"
            IMPORTED_LOCATION "${_shadertool_slang_dir}/bin/slang.dll"
            INTERFACE_INCLUDE_DIRECTORIES "${_shadertool_slang_dir}/include")
    endif()

    # slang.dll is a shim that LoadLibrary's slang-compiler.dll, and the
    # standard modules are searched relative to the DLL: all of them must sit
    # next to the executable.
    set_property(GLOBAL PROPERTY SHADERTOOL_RUNTIME_LIBRARIES
        "${_shadertool_dxc_dir}/bin/x64/dxcompiler.dll"
        "${_shadertool_dxc_dir}/bin/x64/dxil.dll"
        "${_shadertool_d3dcompiler_dir}/bin/x64/d3dcompiler_47.dll"
        "${_shadertool_slang_dir}/bin/slang.dll"
        "${_shadertool_slang_dir}/bin/slang-compiler.dll")
    _shadertool_locate_slang_module_dir("${_shadertool_slang_dir}/bin")
else()
    _shadertool_extract_package(dxc-linux-x64 _shadertool_dxc_dir)
    _shadertool_extract_package(slang-linux-x64 _shadertool_slang_dir)

    if(NOT TARGET ShaderTool::dxcompiler)
        add_library(ShaderTool::dxcompiler SHARED IMPORTED GLOBAL)
        # Sources include <dxcapi.h>, which lives in include/dxc/ in the Linux
        # package; include/ is added too for <dxc/...> spellings (WinAdapter.h,
        # Support/ErrorCodes.h).
        set_target_properties(ShaderTool::dxcompiler PROPERTIES
            IMPORTED_LOCATION "${_shadertool_dxc_dir}/lib/libdxcompiler.so"
            INTERFACE_INCLUDE_DIRECTORIES
                "${_shadertool_dxc_dir}/include/dxc;${_shadertool_dxc_dir}/include")
    endif()

    # The real library file carries its own full name as SONAME
    # (libslang-compiler.so.0.<version>), so linking by full path works and no
    # symlinks are needed at runtime. The libslang.so / libslang-compiler.so.0
    # symlink members may have been skipped during extraction on Windows-made
    # checkouts; glob only the versioned real file.
    file(GLOB _shadertool_slang_libs
        "${_shadertool_slang_dir}/lib/libslang-compiler.so.0.*")
    list(LENGTH _shadertool_slang_libs _shadertool_slang_lib_count)
    if(NOT _shadertool_slang_lib_count EQUAL 1)
        message(FATAL_ERROR
            "ShaderTool: expected exactly one libslang-compiler.so.0.* under "
            "${_shadertool_slang_dir}/lib, found: ${_shadertool_slang_libs}")
    endif()
    list(GET _shadertool_slang_libs 0 _shadertool_slang_lib)

    if(NOT TARGET ShaderTool::slang)
        add_library(ShaderTool::slang SHARED IMPORTED GLOBAL)
        set_target_properties(ShaderTool::slang PROPERTIES
            IMPORTED_LOCATION "${_shadertool_slang_lib}"
            INTERFACE_INCLUDE_DIRECTORIES "${_shadertool_slang_dir}/include")
    endif()

    set_property(GLOBAL PROPERTY SHADERTOOL_RUNTIME_LIBRARIES
        "${_shadertool_dxc_dir}/lib/libdxcompiler.so"
        "${_shadertool_slang_lib}")
    _shadertool_locate_slang_module_dir("${_shadertool_slang_dir}/lib")
endif()

# ---------------------------------------------------------------------------
# shadertool_copy_runtime_libraries(<target>)
#
# Copies every runtime dependency (compiler DLLs/DSOs and the slang standard
# module directory) next to <target>'s output file after each build. On
# non-Windows platforms additionally sets BUILD_RPATH/INSTALL_RPATH to $ORIGIN
# so the copied shared objects are found at runtime.
# ---------------------------------------------------------------------------
function(shadertool_copy_runtime_libraries target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR
            "shadertool_copy_runtime_libraries: no such target: ${target}")
    endif()
    get_property(runtime_libraries GLOBAL PROPERTY SHADERTOOL_RUNTIME_LIBRARIES)
    get_property(module_dir GLOBAL PROPERTY SHADERTOOL_SLANG_STANDARD_MODULE_DIR)
    cmake_path(GET module_dir FILENAME module_dir_name)
    if(NOT WIN32)
        set_target_properties("${target}" PROPERTIES
            BUILD_RPATH "$ORIGIN"
            INSTALL_RPATH "$ORIGIN")
    endif()
    add_custom_command(TARGET "${target}" POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different
            ${runtime_libraries} "$<TARGET_FILE_DIR:${target}>"
        COMMAND "${CMAKE_COMMAND}" -E copy_directory
            "${module_dir}" "$<TARGET_FILE_DIR:${target}>/${module_dir_name}"
        COMMENT "Copying ShaderTool runtime libraries next to ${target}"
        VERBATIM)
endfunction()
